### ISSUE TITLE
Unable to Save Traces

### ISSUE THREAD

**Issue by NorthLand2** [lachlangrose/GeoTools#5]
Unable to save traces to empty shapefile. Get the following error on stopping digitizing and clicking yes on prompt to save trace.
1	Traceback (most recent call last):
			  File "C:/Users/PC/.qgis2/python/plugins\GeoTrace\geo_trace_dialog.py", line 368, in toggle_trace_tool
			    self.deactivateTrace()
			  File "C:/Users/PC/.qgis2/python/plugins\GeoTrace\geo_trace_dialog.py", line 308, in deactivateTrace
			    self.tracetool.addLine()
			  File "C:/Users/PC/.qgis2/python/plugins\GeoTrace\gttracetool.py", line 216, in addLine
			    intval=dem_rb.ReadAsArray(px,py,1,1)[0][0]
			TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by samthiele** [comment]
Thanks @NorthLand2 - the problem seems to occur when loading the DEM into memory (for plane-fitting). Can you confirm you've got the "Fit planes" dialog checked (and the associated DEM layer selected)? Does the DEM cover the area you are trying to trace? 

And can you save traces with the "Fit planes" dialog unchecked? If so it's clearly an issue with our code's handling of the DEM - it would be great if you could share the DEM/cost function you are using with us so we can try replicate the issue?

Cheers,
Sam
